/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package criminal_record;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Aishwarya Waghchoure
 */
public class Create extends javax.swing.JFrame {
    
     Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;

    /**
     * Creates new form Create
     */
    public Create() {
        initComponents();
         Toolkit tk=Toolkit.getDefaultToolkit();
       /* int xsize=(int) tk.getScreenSize().getWidth();
        int ysize=(int) tk.getScreenSize().getHeight();*/
        this.setSize(660,500);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jButton1 = new javax.swing.JButton();
        jfir_id = new javax.swing.JTextField();
        Jcriminal_name = new javax.swing.JTextField();
        jcity = new javax.swing.JTextField();
        jcrime_committed = new javax.swing.JTextField();
        jdate_lodged = new javax.swing.JTextField();
        jspan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 300, 30, 30));
        setLocation(new java.awt.Point(600, 100));
        getContentPane().setLayout(null);

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 280, 124, 25);
        getContentPane().add(jfir_id);
        jfir_id.setBounds(161, 13, 165, 30);

        Jcriminal_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jcriminal_nameActionPerformed(evt);
            }
        });
        getContentPane().add(Jcriminal_name);
        Jcriminal_name.setBounds(161, 53, 165, 30);
        getContentPane().add(jcity);
        jcity.setBounds(161, 88, 165, 30);
        getContentPane().add(jcrime_committed);
        jcrime_committed.setBounds(161, 122, 165, 49);
        getContentPane().add(jdate_lodged);
        jdate_lodged.setBounds(161, 181, 165, 30);
        getContentPane().add(jspan);
        jspan.setBounds(161, 221, 165, 30);

        jLabel1.setText("FIR ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 19, 100, 16);

        jLabel2.setText("Criminal Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 56, 100, 16);

        jLabel3.setText("City");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 91, 100, 16);

        jLabel4.setText("Crime Committed");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 138, 100, 16);

        jLabel5.setText("Date Lodged");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 192, 100, 16);

        jLabel6.setText("Punishment Span");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 232, 100, 16);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 400, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jcriminal_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jcriminal_nameActionPerformed
        // TODO add your handling code here:
       
			
    }//GEN-LAST:event_Jcriminal_nameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         conn = MySqlConnect.ConnectDB();
        
        String sql= "insert into Criminal_Details values (?,?,?,?,?,?)";
        try{
            PreparedStatement stmt = conn.prepareStatement(sql);
			stmt.setString(1,jfir_id.getText());
			stmt.setString(2,Jcriminal_name.getText());
                        stmt.setString(3,jcity.getText());
                        stmt.setString(4,jcrime_committed.getText());
                        stmt.setString(5,jdate_lodged.getText());
			stmt.setString(6,jspan.getText());
                        
			stmt.executeUpdate();
                        //JOptionPane.showMessageDialog(rootPane,"Data inserted Successfully! go back!");
                        this.setVisible(false);
                        create1 c1=new create1();
                        c1.jfir.setText(this.jfir_id.getText());
                        c1.setVisible(true);
                        
        }catch(Exception  e){
            JOptionPane.showMessageDialog(rootPane,"Exception");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jcriminal_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jcity;
    private javax.swing.JTextField jcrime_committed;
    private javax.swing.JTextField jdate_lodged;
    private javax.swing.JTextField jfir_id;
    private javax.swing.JTextField jspan;
    // End of variables declaration//GEN-END:variables
}
