/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package criminal_record;

import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author Aishwarya Waghchoure
 */
public class Login extends javax.swing.JFrame {
Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        /*int xsize=(int) tk.getScreenSize().getWidth();
        int ysize=(int) tk.getScreenSize().getHeight();*/
        this.setSize(660,680);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLogin = new javax.swing.JButton();
        jLoginId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jExit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jn_civilian = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jn_passwd = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        setBounds(new java.awt.Rectangle(0, 0, 660, 680));
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(660, 680));
        getContentPane().setLayout(null);

        jLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLogin.setLabel("LOGIN");
        jLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jLogin);
        jLogin.setBounds(390, 220, 140, 41);

        jLoginId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginIdActionPerformed(evt);
            }
        });
        getContentPane().add(jLoginId);
        jLoginId.setBounds(440, 100, 180, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin LoginId");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 100, 180, 22);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 160, 120, 22);
        getContentPane().add(jPassword);
        jPassword.setBounds(440, 160, 180, 30);

        jExit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jExit.setText("Exit");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        getContentPane().add(jExit);
        jExit.setBounds(320, 600, 70, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Username");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 340, 130, 16);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 400, 120, 16);
        getContentPane().add(jn_civilian);
        jn_civilian.setBounds(210, 330, 170, 40);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 460, 140, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Click here to create new citizens account");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 540, 320, 16);
        getContentPane().add(jn_passwd);
        jn_passwd.setBounds(210, 390, 170, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Login as administrator");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(280, 40, 370, 28);

        jLabel8.setIcon(new javax.swing.ImageIcon("F:\\PHOTOS\\a.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 250, 270);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Login as a citizen");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(150, 280, 350, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\imgonline-com-ua-resize-BsW00lqcnjHVEoJ.jpg")); // NOI18N
        jLabel3.setText("Login in as Administrator");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 660, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginActionPerformed
        // TODO add your handling code here:
        String LoginId=jLoginId.getText();
        String password=jPassword.getText();
        
         conn = MySqlConnect.ConnectDB();
         
        
        String sql="Select * from Administrators where Username =?";
        try{
                    String get_username,get_password;

            PreparedStatement pst=conn.prepareStatement(sql);
            pst.setString(1,jLoginId.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                get_username=rs.getString("Username");
                
                  get_password=rs.getString("Password");
                  if(LoginId.contentEquals(get_username) && password.contentEquals(get_password))
            {
                new tabbed_frame().setVisible(true);
                this.setVisible(false);
            }
                
            }
          
            
        }catch(Exception E){
            JOptionPane.showMessageDialog(rootPane,"Error"+E);
        }
     
        
      /*  if(LoginId.contains("admin") && password.contains("123"))
        {
            
            jLoginId.setText(null);
            jPassword.setText(null);
            systemExit();
            
            new Choose_Option().setVisible(true);
            
            
            
            
        }
        else
        {    JOptionPane.showMessageDialog(rootPane, "Wrong Username or password");
            System.out.println("unsuccessful");
        }*/
    }//GEN-LAST:event_jLoginActionPerformed

    private void jLoginIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginIdActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jExitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String LoginId=jn_civilian.getText();
        String password=jn_passwd.getText();
        
         conn = MySqlConnect.ConnectDB();
         
        
        String sql="Select * from Civilian where Username =?";
        try{
                    String get_username,get_password,get_name,get_surname;

            PreparedStatement pst=conn.prepareStatement(sql);
            pst.setString(1,jn_civilian.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                get_username=rs.getString("Username");
                
                  get_password=rs.getString("Password");
                  
                  get_name=rs.getString("Name");
                  get_surname=rs.getString("Surname");
                  if(LoginId.contentEquals(get_username) && password.contentEquals(get_password))
            {
                Lodge_Complaint lc=new Lodge_Complaint();
                lc.jname.setText(get_name);
                lc.jsurname.setText(get_surname);
                lc.setVisible(true);
            }
                
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane,"Wrong username or password.Create new account if You don't have any.");
            }
          
            
        }catch(Exception E){
            JOptionPane.showMessageDialog(rootPane,"Error"+E);
        }
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        new Create_Civilian_Account().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
        // End of variables declaration                   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLogin;
    private javax.swing.JTextField jLoginId;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jn_civilian;
    private javax.swing.JPasswordField jn_passwd;
    // End of variables declaration//GEN-END:variables
private void systemExit()
{
    WindowEvent winCloseing=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
}
}



